version: "3.7"

services:

  webpack:
    build:
      context: ./webpack
      args:
        NODE_VERSION: ${NODE_VERSION?}
    volumes:
      - ./webpack:/usr/local/src
      - node_modules:/usr/local/src/node_modules
    ports:
      - "${WEBPACK_DEV_SERVER_PORT:-8080}:8080"
    networks:
      - webpacky-network
    command: "npx webpack-dev-server --mode development --host 0.0.0.0 --disable-host-check --hot"


volumes:
  node_modules:
    driver: local

networks:
  webpacky-network:
