# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rack"
gem "webpacky", git: "git://github.com/ak10m/webpacky.git", branch: "master"
